button_g=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_h=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_i=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_j=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_k=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_l=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_m=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_n=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_o=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_p=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_q=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_r=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_s=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_t=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_u=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_v=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_w=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_x=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_y=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_z=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_aa=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ab=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ac=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ad=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ae=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_af=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ag=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ah=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_ai=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)
button_aj=Button(window,text="Taylor Swift",image=pic,padx=40, pady=20)



#*********************************************************************************
button_g.grid(row=2 , column=1)
button_h.grid(row=2 , column=2)
button_i.grid(row= 2, column=3)
button_j.grid(row= 2, column=4)
button_k.grid(row= 3, column=0)
button_l.grid(row= 3, column=1)
button_m.grid(row= 3, column=2)
button_n.grid(row= 3, column=3)
button_o.grid(row= 3, column=4)
button_p.grid(row= 4, column=0)
button_q.grid(row= 4, column=1)
button_r.grid(row= 4, column=2)
button_s.grid(row= 4, column=3)
button_t.grid(row= 4, column=4)
button_u.grid(row= 5, column=0)
button_v.grid(row= 5, column=1)
button_w.grid(row= 5, column=2)
button_x.grid(row= 5, column=3)
button_y.grid(row= 5, column=4)
button_z.grid(row= 6, column=0)
button_aa.grid(row= 6, column=1)
button_ab.grid(row= 6, column=2)
button_ac.grid(row= 6, column=3)
button_ad.grid(row= 6, column=4)
button_ae.grid(row= 7, column=0)
button_af.grid(row= 7, column=1)
button_ag.grid(row= 7, column=2)
button_ah.grid(row= 7, column=3)
button_ai.grid(row= 7, column=4)
button_aj.grid(row= 8, column=0)
#************************************************************************************
label_title=Label(window, text="WELCOME TO THE GUESS WHO GAME !", font=("typewriter", 35), bg='black',fg='white')
label_title.pack()
label_subtitle=Label(window, text="click below to start ", font=("typewriter", 25), bg='black',fg='white')
label_subtitle.pack()
button1=Button(window, text="start now!", font=('typewriter', 25), command=tab2)
button1.pack(side=TOP)
frame.pack(expand=YES)